# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: Yann Ilboudo # the website title (if blank, full name will be used instead)
first_name: Yann
middle_name: 
last_name: Ilboudo
email: yilboudo@gmail.com
description: Bioinformatics > # the ">" symbol means to ignore newlines until "footer_text:"

footer_text: >
  Powered by <a href="https://jekyllrb.com/" target="_blank">Jekyll</a> with <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme.
  Hosted by <a href="https://pages.github.com/" target="_blank">GitHub Pages</a>.
  Photos from <a href="https://unsplash.com" target="_blank">Unsplash</a>.
keywords: jekyll, jekyll-theme, academic-website, portfolio-website # add your own keywords or leave empty
lang: en # the language of your site (for example: en, fr, cn, ru, etc.)
icon: ⚛️ # the emoji used as the favicon (alternatively, provide image name in /assets/img/)

url: https://yannilboudo.github.io # the base hostname & protocol for your site
baseurl:  # the subpath of your site, e.g. /blog/. Leave blank for root
last_updated: false # set to true if you want to display last updated in the footer
impressum_path: # set to path to include impressum link in the footer, use the same path as permalink in a page, helps to conform with EU GDPR
back_to_top: true # set to false to disable the back to top button

author:
  name:
    en: Yann Ilboudo
  description:
    en: 
  emails: 
   - yann.ilboudo [at] ladydavis.ca
  twitter: Yann_Speaks
  github: yilboudo
  orcid: 0000-0002-8809-0922
  gscholar: https://scholar.google.com/citations?user=oFa4ymkAAAAJ&hl=en&oi=ao
  pubmed: https://www.ncbi.nlm.nih.gov/myncbi/14kFYxHmdlvQx/bibliography/public/

# Build settings
# markdown: redcarpet
# highliter: rouge
exclude: ["Gemfile", "Gemfile.lock", "Rakefile", "README.md", "scripts", ".DS_Store", ".jekyll-cache"]
sass:
    sass_dir: ./css

# redcarpet settings
redcarpet:
  extensions: [tables,autolink,strikethrough,no_intra_emphasis,superscript,highlight,with_toc_data]

# jekyll-scholar settings
scholar:
  bibtex_filters:
    - latex
    
  style: ./_bibliography/custom.csl
  locale: en

  sort_by: none
  order: ascending

  source: ./_bibliography
  bibliography: publications.bib
  bibliography_template: "{{reference}}"
#   bibliography_list_attributes:
#     reversed:

  replace_strings: true
  join_strings:    true

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"
