version: 2.1
orbs:
  aws-s3: circleci/aws-s3@3.0.0

jobs:
  build:
    docker:
      - image: cimg/ruby:3.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: bundle install
      - run:
          name: Jekyll build
          command: bundle exec jekyll build
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - attach_workspace:
          at: .
      - aws-s3/sync:
          arguments: '--delete --dryrun'
          from: ./_site/
          to: 's3://henriquesantosorg'

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          context: aws-context
#          filters:
#            branches:
#              only: master