# config.yml
backend:
  name: github
  repo: gungsatya/gungsatya.github.io # Path to your GitHub repository
  # optional, defaults to master
  branch: master
  site_domain: pensive-jang-bb39ae.netlify.app
media_folder: "assets/uploads"
collections:
  - name: "posts"
    label: "Posts"
    folder: "_posts/"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: true
    fields:
      - {
          label: "Layout",
          name: "layout",
          widget: "select",
          options: ["distill", "post"],
          default: "post",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Tags", name: "tags", widget: "string", required: false }
      - {
          label: "Categories",
          name: "categories",
          widget: "string",
          required: false,
        }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - {
          label: "Author",
          name: "author",
          widget: "relation",
          collection: "authors",
          search_fields: ["name"],
          value_field: "name",
        }
      - { label: "TOC", name: "toc", widget: "hidden", default: true }
      - {
          label: "Comments",
          name: "comments",
          widget: "boolean",
          default: true,
        }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "authors"
    label: "Authors"
    folder: "_authors/"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Site URL", name: "site_url", widget: "string" }
      - {
          label: "Affiliation",
          name: "affiliation",
          widget: "relation",
          collection: "affiliations",
          search_fields: ["name"],
          value_field: "name",
        }
  - name: "affiliations"
    label: "Affiliations"
    folder: "_affiliations/"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Name", name: "name", widget: "string" }
  - name: "news"
    label: "News"
    folder: "_news/"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "date" }
      - { label: "Inline", name: "inline", widget: "boolean", default: true }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "projects"
    label: "Projects"
    folder: "_projects/"
    slug: "{{year}}-{{slug}}"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "page" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Date", name: "date", widget: "string" }
      - { label: "Image", name: "img", widget: "image", allow_multiple: false }
      - {
          label: "Importance",
          name: "importance",
          widget: "number",
          min: 0,
          max: 5,
        }
      - {
          label: "Category",
          name: "category",
          widget: "select",
          options: ["work", "fun"],
        }
      - { label: "Body", name: "body", widget: "markdown" }
