name: Deploy
on:
  push:
    branches:
      - master
      - source
  pull_request:
    branches:
      - master
      - source
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2' # Upgrade from 2.7 to 3.2
        bundler-cache: true # This caches dependencies automatically
    - name: Setup deploy options
      id: setup
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        if [[ ${GITHUB_REF} = refs/pull/*/merge ]]; then # pull request
          echo "SRC_BRANCH=${GITHUB_HEAD_REF}" >> $GITHUB_OUTPUT
          echo "NO_PUSH=--no-push" >> $GITHUB_OUTPUT
        elif [[ ${GITHUB_REF} = refs/heads/* ]]; then # branch, e.g. master, source etc
          echo "SRC_BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
        fi
        if [[ ${{ github.repository }} = *.github.io ]]; then # user/org repo
          echo "DEPLOY_BRANCH=master" >> $GITHUB_OUTPUT
        else
          echo "DEPLOY_BRANCH=gh-pages" >> $GITHUB_OUTPUT
        fi
    - name: Fix line endings and commit changes
      run: |
        sed -i 's/\r$//' bin/deploy
        chmod +x bin/deploy
        git add bin/deploy
        git commit -m "Fix line endings in deploy script" || echo "No changes to commit"
    - name: Deploy website 
      run: |
        bin/deploy --verbose ${{ steps.setup.outputs.NO_PUSH }} \
          --src ${{ steps.setup.outputs.SRC_BRANCH }} \
          --deploy ${{ steps.setup.outputs.DEPLOY_BRANCH }} < <(echo y)
