name: deploy

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2.1'
        bundler-cache: true
    - name: Install deps
      run: |
        npm install -g mermaid.cli
    - name: Build site
      run: |
        bundle exec jekyll build
    - name: Deploy website
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: _site
