name: Docker Image CI

on:
  push:
    branches: [ master, add-dockerslim ]


jobs: 

  build:

    runs-on: ubuntu-latest
    #if: github.repository_owner == 'alshedivat'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      
    - name: Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
         
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        platforms: linux/amd64,linux/arm64/v8
        tags: amirpourmand/al-folio

    - name: update docker-compose
      shell: bash
      run:  |
        sed -i "s|\.:|${{ github.workspace }}:|g" ${{ github.workspace }}/docker-compose.yml 
        cat ${{ github.workspace }}/docker-compose.yml 
        
    - uses: kitabisa/docker-slim-action@v1.0.3
      env:
        DSLIM_COMPOSE_FILE: ${{ github.workspace }}/docker-compose.yml
        DSLIM_TARGET_COMPOSE_SVC: jekyll
        DSLIM_CONTINUE_AFTER: signal
      with:
        target: amirpourmand/al-folio
        tag: "slim"

    # Push to the registry
    - run: docker image push amirpourmand/al-folio:slim
