name: Docker Slim

#Only trigger, when the build workflow succeeded
# on:
#   workflow_run:
#     workflows: ["Docker Image CI"]
#     types:
#       - completed

on: 
  push:
    branches: 
      - '**'

jobs: 
  build:
    runs-on: ubuntu-latest
    #if: github.repository_owner == 'alshedivat'

    defaults:
      run:
        working-directory: ${{ github.workspace }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: update docker-compose
      shell: bash
      run:  |
        sed -i "s|\.:|${{ github.workspace }}:|g" ${{ github.workspace }}/docker-compose.yml 
        cat ${{ github.workspace }}/docker-compose.yml 
        
    - uses: kitabisa/docker-slim-action@v1
      env:
        #DSLIM_HTTP_PROBE: false
        DSLIM_PULL: true
        DSLIM_COMPOSE_FILE: ${{ github.workspace }}/docker-compose.yml
        DSLIM_TARGET_COMPOSE_SVC: jekyll
      with:
        target: amirpourmand/al-folio
        tag: "slim"
