name: GitHub Pages

on:
  push:
    branches:
      - main  # Replace 'main' with the branch you want to trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.0'  # Replace with the Ruby version you need

      - name: Install dependencies
        run: |
          bundle install

      - name: Build the site
        run: |
          bundle exec jekyll build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
