name: Lighthouse Badger Workflow

on:
  page_build:
  workflow_dispatch:

env:
  URLS: https://alshedivat.github.io/al-folio/
  REPO_BRANCH: Innovai-yonsei/innovai master
  MOBILE_LIGHTHOUSE_PARAMS: --only-categories=performance,accessibility,best-practices,seo --throttling.cpuSlowdownMultiplier=2
  DESKTOP_LIGHTHOUSE_PARAMS: --only-categories=performance,accessibility,best-practices,seo --preset=desktop --throttling.cpuSlowdownMultiplier=1
  REPOSITORY: Innovai-yonsei/innovai
  BRANCH: master

jobs:
  lighthouse-badger:
    runs-on: ubuntu-latest
    timeout-minutes: 8

    steps:
      - name: Checkout Target Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ env.REPOSITORY }}
          ref: ${{ env.BRANCH }}
          token: ${{ secrets.LIGHTHOUSE_BADGER_TOKEN }} # ✅ 보안 토큰 사용

      - name: Checkout Lighthouse Badges Repository
        uses: actions/checkout@v4
        with:
          repository: "myactionway/lighthouse-badges"
          path: temp_lighthouse_badges_nested
          token: ${{ secrets.LIGHTHOUSE_BADGER_TOKEN }} # ✅ 보안 토큰 사용

      - name: Run Lighthouse Badger Action
        uses: myactionway/lighthouse-badger-action@v2.2
        with:
          urls: ${{ env.URLS }}
          mobile_lighthouse_params: ${{ env.MOBILE_LIGHTHOUSE_PARAMS }}
          desktop_lighthouse_params: ${{ env.DESKTOP_LIGHTHOUSE_PARAMS }}
