name: Build Notion Posts

on:
#  schedule:
#  - cron: "*/30 * * * *"
  
  push:
   branches: [ "npm-notion" ]
#  pull_request:
#    branches: [ "note" ]
    
  workflow_dispatch:


jobs:
  build_posts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        if: github.ref == 'refs/heads/notion-to-md-npm'
        with:
          node-version: 15.x
      - name: Run a multi-line script
        if: github.ref == 'refs/heads/notion-to-md-npm'
        run: |
          touch .env
          echo 'NOTION_TOKEN=${{ secrets.NOTION_TOKEN }}' >> .env
          echo 'NOTION_DATABASE_ID=${{ secrets.NOTION_DATABASE_ID }}' >> .env
          yarn
          yarn start
      - uses: stefanzweifel/git-auto-commit-action@v4
        if: github.ref == 'refs/heads/notion-to-md-npm'
        with:
          commit_message: build pages from notion
          push_options: '--force'
          branch: org-testing
